name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          cache: true
          cache-dependency-path: '**/Directory.Packages.props'
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Build
        run: |
          dotnet --info
          dotnet build -c Release
      - name: Test
        run: |
          dotnet test --coverage --coverage-output-format cobertura
          dotnet tool restore
          dotnet tool run reportgenerator -reports:"TestResults/*.cobertura.xml" -targetdir:"coverage" -reporttypes:TextSummary
          [[ -f "./coverage/Summary.txt" ]] && cat "./coverage/Summary.txt"
      - uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
